name: van-crime
channels:
  - conda-forge
  - defaults
dependencies:
  - ipykernel
  - ipython>=7.15
  - altair
  - pandas
  - geopandas
  - numpy
  - utm
  - pip
  - pip:
    - dash
    - dash_bootstrap_components

